### ISSUE TITLE
do_shortcode not workinkg as expected

### ISSUE THREAD

**Issue by HelaGone** [alleyinteractive/anvato#27]
Hello
@srtfisher 
I've been trying to execute the anvplayer shortcode `[anvplayer video="123456" station="My Station"]` inside a custom rss2 feed, but the resulting html is something like this: `<div id='p0'></div><script data-anvp=' ... '></script>` instead of the `iframe `with the right `src` How can I get the right output? 

Here is the situation: 
In my post content I've imported one video which is stored in Anvato with the `Media Explorer plugin`, and in my custom rss2 feed I got something like this: 
`$content = apply_filters('the_content', $post->post_content);` which outputs the post content with the anvplayer shortcode rendered But the result is always an empty div with an id and a script tag beneath with the data-anv object. 

Any help is appreciated 
thanks in advance

**Comment by dlh01** [comment]
The `iframe` is generated by the Anvato player JavaScript loaded by the `script` tag, so it works only where JS is executed. 

You can consult how the `iframe` is built for AMP requests (https://github.com/alleyinteractive/anvato/blob/master/lib/shortcode.php#L202-L216) or the Anvato API documentation (https://dev.anvato.net/api/player#embed-options) to tailor the output for your needs.
